quarkus.smallrye-jwt.enabled=true
smallrye.jwt.sign.key.location=privateKey.pem

# Senhas para usuários mock de desenvolvimento
mock.user.admin.password=admin123
mock.user.client.password=cliente123

# Jacoco Test Coverage Configuration
quarkus.jacoco.report=true
quarkus.jacoco.minimum-line-coverage=0.5