# Configurações do banco de dados postgresql
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=petshop
quarkus.datasource.password=petshop
# quarkus.datasource.jdbc.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/petshop_db
quarkus.hibernate-orm.database.generation=update

# Jacoco Test Coverage Configuration
quarkus.jacoco.report=true
quarkus.jacoco.minimum-line-coverage=0.5

# Configurações iniciais do rabbitmq
rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest

# Envio de agendamento do rabbitmq
mp.messaging.outgoing.appointment-scheduled.connector=smallrye-rabbitmq
mp.messaging.outgoing.appointment-scheduled.exchange.name=appointment-events

mp.messaging.outgoing.appointment-cancelled.connector=smallrye-rabbitmq
mp.messaging.outgoing.appointment-cancelled.exchange.name=appointment-cancelled-events

# Configurações exclusivas para o perfil de Testes
%test.quarkus.datasource.db-kind=postgresql
%test.quarkus.datasource.devservices.enabled=true
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.rabbitmq.devservices.enabled=false